# Generated by Django 3.2.5 on 2021-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(max_length=10)),
                ('pincode', models.IntegerField(max_length=20)),
                ('address', models.TextField()),
                ('speed', models.IntegerField()),
                ('enginestats', models.CharField(max_length=20)),
                ('fuellevel', models.IntegerField()),
            ],
        ),
    ]
