# Generated by Django 3.2.5 on 2021-10-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_add_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avgspeed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='temp',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
