# Generated by Django 3.2.5 on 2021-10-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20211029_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='avgspeed',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='temp',
            field=models.IntegerField(default=''),
        ),
    ]
