# Generated by Django 3.2.5 on 2021-10-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20211028_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='address',
        ),
        migrations.AddField(
            model_name='add',
            name='ownername',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
