# Generated by Django 3.2.5 on 2021-10-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20211028_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Item',
        ),
    ]
